dist: focal
language: c
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install automake autoconf glib; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qq automake autoconf gcc libglib2.0-dev libcurl4-openssl-dev libgtk-3-dev; fi

script:
 - ./autogen.sh && make -j2
