name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        flags: ["--enable-networking --disable-gtk3",
                "--enable-networking --enable-gtk3",
                "--disable-networking"]
        include:
        - os: macos-latest
          flags: "--enable-networking"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: matrix.os == "ubuntu-latest"
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq automake autoconf gcc libglib2.0-dev libcurl4-openssl-dev libgtk2.0-dev libgtk-3-dev
    - name: Build
      run: |
        ./autogen.sh {{ matrix.flags }} && make -j2
    - name: Test
      run: |
        src/dopewars -v
        src/dopewars -h
